user root;
worker_processes auto;
worker_rlimit_nofile 100000;

events {
    worker_connections 16384;
    multi_accept on;
    use epoll;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    server_tokens off;

    client_body_buffer_size 128k;
    client_header_buffer_size 1k;
    client_max_body_size 0;
    large_client_header_buffers 4 16k;

    keepalive_timeout 300s;
    keepalive_requests 10000;
    proxy_connect_timeout 7d;
    proxy_send_timeout 7d;
    proxy_read_timeout 7d;
    send_timeout 7d;

    map $uri $backend_port {
        default           700;
        ~/vlessws         14016;
        ~/vmessws         23456;
        ~/trojanws        25432;
    }

    map $uri $grpc_port {
        ~/xtrojan         33456;
        ~/xvmess          31234;
        ~/xvless          24456;
    }

    server {
        listen       89;
        server_name  127.0.0.1 localhost;
        access_log /var/log/nginx/vps-access.log;
        error_log /var/log/nginx/vps-error.log error;
        root   /home/vps/public_html;

        location / {
            index  index.html index.htm index.php;
            try_files $uri $uri/ /index.php?$args;
        }

  location ~ \.php$ {
    include /etc/nginx/fastcgi_params;
    fastcgi_pass  127.0.0.1:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }
}


    server {
        listen 80;
        listen [::]:80;
        listen 443 ssl reuseport;
        listen [::]:443 ssl reuseport;
        http2 on;

        server_name *.rere.com rere.com;

        ssl_certificate /etc/xray/xray.crt;
        ssl_certificate_key /etc/xray/xray.key;

        ssl_session_cache shared:SSL:50m;
        ssl_session_timeout 1d;
        ssl_session_tickets on;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers on;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_buffering off;
        proxy_request_buffering off;

        location ~* (xtrojan|xvmess|xvless) {
            rewrite ^.*(xtrojan|xvmess|xvless)(/.*)?$ /$1$2 break;

            grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            grpc_read_timeout 7d;
            grpc_send_timeout 7d;

            grpc_pass grpc://127.0.0.1:$grpc_port;
        }

        location / {
            rewrite ^.*(vlessws|vmessws|trojanws).*$ /$1 break;

            proxy_buffer_size 4k;
            proxy_buffers 4 32k;
            proxy_busy_buffers_size 64k;

            proxy_pass http://127.0.0.1:$backend_port;
        }
    }
}
