#!/bin/bash
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lyellow='\e[93m'
Lgreen='\e[92m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/mylo1998/ijin/refs/heads/main/Mylo"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      ${GREEN}TELEGRAM${NC} https://t.me/EncikKatakvps"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit 0
  fi
}
checking_sc
clear
online-ip(){

clear

echo -e "${CYAN}╭══════════════════════════════════╮${NC}"
echo -e "${CYAN}│   XRAY ONLINE + IP LIMIT         │${NC}"
echo -e "${CYAN}╰══════════════════════════════════╯${NC}"


LOG="/var/log/xray/access.log"
DB="/etc/xray/iplimit.db"

mkdir -p /etc/xray
touch $DB


users=$(grep -E "^#vlg#|^#vmg#" /etc/xray/config.json | awk '{print $2}' | sort -u)


for user in $users
do

data=$(grep -w "email: $user" $LOG | tail -50)


if [[ ! -z "$data" ]]; then


IP=$(echo "$data" | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}' | sort -u)

COUNT=$(echo "$IP" | wc -l)


TYPE="VLESS"

grep -q "^#vmg# $user" /etc/xray/config.json && TYPE="VMESS"


echo -e "${BLUE}━━━━━━━━━━━━━━━━━━${NC}"

echo -e "USER     : ${YELLOW}$user${NC}"
echo -e "PROTOCOL : $TYPE"

echo -e "IP LIMIT : 1"

echo -e "IP AKTIF :"
echo "$IP"


OLD=$(grep "^$user " $DB | awk '{print $2}')


if [[ -z "$OLD" ]]; then

echo "$user $IP" >> $DB

echo -e "STATUS   : ${GREEN}LOCK IP${NC}"


elif [[ "$OLD" != "$IP" ]]; then

echo -e "STATUS   : ${RED}IP BERUBAH${NC}"


else

echo -e "STATUS   : ${GREEN}OK${NC}"

fi


fi

done


echo ""
read -n1 -s -r -p "Press any key back menu"

menu

}

